// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://adklmrgrjhqanlauhylk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFka2xtcmdyamhxYW5sYXVoeWxrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxODczMjcsImV4cCI6MjA2ODc2MzMyN30.ktuzKui0YT2-oRYJC6k4c6We6iIe8nAew8BDb7Fh2zI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});